apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # Full name of the resource. It must match the spec fields below in the form: <plural>.<group>
  name: persons.extensions.helanto.co
spec:
  # Either Namespaced or Cluster
  scope: Namespaced
  group: extensions.helanto.co
  versions:
    - name: v1
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                age:
                  type: integer
                socialSecurityNumber:
                  type: integer
  names:
    # The CamelCased singular type
    kind: Person
    # Singular name to be used as an alias on the CLI and for display
    singular: person
    # Plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: persons
    