apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-name
  namespace: default
subjects:
  - kind: ServiceAccount
    name: serviceaccount-name
    namespace: default
roleRef:
  kind: Role
  name: role-name
  apiGroup: rbac.authorization.k8s.io
