apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev

namespace: default

commonLabels:
  env: development

resources:
  - pod.yaml
  - service-account.yaml
  - role.yaml
  - binding.yaml
