apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
    env: development
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 80
      nodePort: 30090