apiVersion: v1
kind: Pod
metadata:
  name: postgres-server
spec:
  containers:
  - name: postgres-container
    resources:
      requests:
        cpu: "0.2"
        memory: "256Mi"
      limits:
          cpu: "0.5"
          memory: "512Mi"
