apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    env: development
  annotations:
    kubernetes.io/change-cause: "nginx:1.19.9"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  replicas: 3
  # Replica set selection rules.
  selector:
    matchLabels:
      app: nginx
  # Pod template
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        env: development
    spec:
      containers:
      - name: nginx-container
        imagePullPolicy: "IfNotPresent"
        image: nginx:1.19.9
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "0.1"
            memory: "128Mi"
          limits:
            cpu: "0.1"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
          failureThreshold: 3
