apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
      app: nginx
      env: development
spec:
  containers:
  - image: nginx:1.19.9
    imagePullPolicy: "IfNotPresent"
    name: nginx-container
    ports:
      - containerPort: 80
    resources:
      requests:
        cpu: "0.2"
        memory: "128Mi"
      limits:
          cpu: "0.5"
          memory: "256Mi"
    livenessProbe:
      httpGet:
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 20
      failureThreshold: 3