apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "person-operator.bindingName" . }}
  labels:
    {{- include "person-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "person-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "person-operator.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
