apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev

namespace: default

commonLabels:
  env: development

resources:
  - database.yaml
  - service.yaml

patchesStrategicMerge:
  - patches/set-resources.yaml

configMapGenerator:  
  - name: postgres-configuration
    literals:
      - username=helias
      - password=helias
      - database=db

generatorOptions:
  # disableNameSuffixHash is true disables the default behavior of adding a
  # suffix to the names of generated resources that is a hash of
  # the resource contents.
  disableNameSuffixHash: true

images:
  - name: postgres-image # Match images with this image name
    newName: postgres
    newTag: "12.2"