apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
spec:
  clusterIP: None # create a headless service
  type: ClusterIP
  selector:
    app: database
  ports:
    # In headless service we require "port = targetPort"
    - protocol: TCP
      port: 5432
      targetPort: 5432