name: Person operator

on:
  push:
    branches: [ master ]

jobs:
  project-version:
    name: Project version

    outputs:
      version: ${{ steps.extract-version.outputs.version }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract version
      id: extract-version
      run: |
        cd ./custom-resource/app
        PROJECT_VERSION=$(sbt -Dsbt.log.noformat=true clean version | tail -1 | awk '{print $2}')
        echo "::set-output name=version::$PROJECT_VERSION"
      shell: bash
  
  build-app:
    name: Build application

    needs: project-version

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Harbor
      uses: docker/login-action@v1
      with:
        logout: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      id: docker_build_push
      with:
          push: true
          context: ./custom-resource/app
          file: ./custom-resource/app/docker/build/Dockerfile
          tags: heliasantoniou/person-operator:latest,heliasantoniou/person-operator:${{ needs.project-version.outputs.version }}

    - name: Image digest
      run: echo "${{ steps.docker_build_push.outputs.digest }}"
